### PR TITLE
update setting image

### PR DESCRIPTION
**Pull request by YahangWu**
*Issue #, if available:*

*Description of changes:

The setting image in the readme.md is not relevant anymore

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by PatMyron** [comment]
> The setting image in the readme.md is not relevant anymore

Why is it no longer relevant?

**Comment by YahangWu** [comment]
Hi Pat, the command showed in the original image is not working anymore

**Comment by YahangWu** [comment]
> > The setting image in the readme.md is not relevant anymore
> 
> Why is it no longer relevant?

> Hi Pat, the command showed in the original image is not working anymore

That's why I added the pull request and updated the image

**Comment by PatMyron** [comment]
@YahangWu sorry for the late response, tested the command in the original image and was not able to reproduce any issue

**Comment by YahangWu** [comment]
> @YahangWu sorry for the late response, tested the command in the original image and was not able to reproduce any issue

Hi @PatMyron , it's showing ```[cfn-lint] /bin/sh: --ignore-checks: command not found

Go to https://github.com/aws-cloudformation/cfn-python-lint/#install for more help``` for me

**Comment by PatMyron** [comment]
@YahangWu what did you have set as your path when you ran into that?

**Comment by YahangWu** [comment]
@PatMyron I am using anaconda 3, and cfn-lint path is ```/usr/local/bin/cfn-lint```, I have no issue running cfn-lint tho, if I provide the setting like ```cfn-lint -c E3012 -i E3012```

**Pull request closed without merging**
