### PR TITLE
Update packages to versions of 2020.11.03

### PR DESCRIPTION
**Pull request by kddejong**
*Issue #, if available:*

*Description of changes:*
- Update the packages to what 2020.11.03

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by PatMyron** [comment]
@kddejong is there a command run to automatically update these? Or are these manual upgrades?

**Comment by kddejong** [comment]
I ran npm update in the root, client, and server folders.

**Comment by PatMyron** [comment]
Could set up [Dependabot](https://dependabot.com/) or Github actions to regularly open these PRs

**Comment by PatMyron** [comment]
replaced by https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/pull/144

**Pull request closed without merging**
